### ISSUE TITLE
Username Change Request

### ISSUE THREAD

**Issue by andysinclair** [pyrocumulus/Sick-Beard#3]
Hi sharpcloud,
Sorry about creating a github issue for this, I wasn't sure how else I could contact you as your email address is private.
I would like to ask you if you could change your github username to something else? I work at SharpCloud Software (http://www.sharpcloud.com) and am trying to create a github organisation called sharpcloud. I cannot do this as your account is called sharpcloud. Would you be willing to change your username?

Regards,

Andrew Sinclair
email: andrew@sharpcloud.com

**Comment by sharpcloud** [comment]
Hey Andrew,

I'll see what I can do. I do use this specific name in some other places as well and I'd like to have the same name across those sites.


Regards,

Marcel

**Comment by andysinclair** [comment]
Hi Marcel,

Thanks for getting back to me, I understand that you will need to change some references to that name. It would be great if you could change it - we would really appreciate it :-)

Thanks,

Andy

**Comment by pyrocumulus** [comment]
Hi Andy,

Found something else I can work with. Wasn't that attached to the old name so :) The name is now available for registration.


Regards,

Marcel

**Comment by andysinclair** [comment]
Hi Marcel,

Thanks very much, I really appreciate it!
Good luck with your development,

Regards,

Andy
